name: '📦 MVP Task'
description: 'Create a structured task for a feature, subfeature, or milestone from the Nobd roadmap.'
title: '[MVP#] Short descriptive title'
labels: ['mvp', 'feature']
body:
    - type: markdown
      attributes:
          value: |
              ### 📘 MVP Task Template
              Use this template for all development tasks derived from the Nobd roadmap.
              Fill in every section so tracking and linking (PRs, commits) is consistent.

    - type: input
      id: mvp
      attributes:
          label: '🧭 MVP Phase'
          description: 'Which MVP does this task belong to? (e.g., MVP0, MVP1, MVP2, etc.)'
          placeholder: 'MVP0'

    - type: input
      id: section
      attributes:
          label: '📂 Section'
          description: 'Subsystem or domain (frontend, backend, database, design, etc.)'
          placeholder: 'frontend'

    - type: textarea
      id: summary
      attributes:
          label: '📝 Summary'
          description: 'Short description of what this task does and why it matters.'

    - type: textarea
      id: description
      attributes:
          label: '📋 Detailed Description'
          description: 'Steps, logic, or reasoning for this task. Include references to roadmap sections if applicable.'

    - type: textarea
      id: acceptance
      attributes:
          label: '✅ Acceptance Criteria'
          description: 'List of concrete, verifiable criteria to mark this task as done.'
          placeholder: "- [ ] UI matches design\n- [ ] Tests pass\n- [ ] Lint passes"

    - type: textarea
      id: deliverables
      attributes:
          label: '📦 Deliverables'
          description: 'Expected outputs — files, features, screenshots, tests, etc.'

    - type: textarea
      id: notes
      attributes:
          label: '💬 Notes or Discussion'
          description: 'Anything worth noting for future reference (implementation details, gotchas, dependencies).'
